apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: staging
  labels:
    app: demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: nginx:1.27
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: production
